"use client"
import { useState, useEffect } from "react"
import { useRouter, useParams } from "next/navigation"
import Link from "next/link"

export default function StudentProfilePage() {
  const router = useRouter()
  const params = useParams()
  const id = params.id as string
  const [student, setStudent] = useState<any>(null)
  const [grades, setGrades] = useState<any[]>([])
  const [attendance, setAttendance] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [deleting, setDeleting] = useState(false)
  const [generatingID, setGeneratingID] = useState(false)

  useEffect(() => {
    fetch(`/api/students/${id}`)
      .then(res => res.json())
      .then(data => {
        setStudent(data.student)
        setGrades(data.grades)
        setAttendance(data.attendance)
        setLoading(false)
      })
      .catch(() => setLoading(false))
  }, [id])

  const handleDelete = async () => {
    if (!confirm("Are you sure you want to delete this student?")) return
    setDeleting(true)
    try {
      const res = await fetch(`/api/students/${id}`, { method: "DELETE" })
      if (res.ok) router.push("/dashboard/students")
    } catch {
      setDeleting(false)
    }
  }

  const generateIDCard = async () => {
    setGeneratingID(true)
    try {
      const { default: jsPDF } = await import("jspdf")
      const doc = new jsPDF({
        orientation: "landscape",
        unit: "mm",
        format: [85.6, 53.98]
      })

      // Background
      doc.setFillColor(37, 99, 235)
      doc.rect(0, 0, 85.6, 18, "F")

      // School name
      doc.setTextColor(255, 255, 255)
      doc.setFontSize(7)
      doc.setFont("helvetica", "bold")
      const schoolName = student.school?.name || "JETS School"
      doc.text(schoolName.toUpperCase(), 42.8, 8, { align: "center" })
      doc.setFontSize(5)
      doc.setFont("helvetica", "normal")
      doc.text("STUDENT IDENTIFICATION CARD", 42.8, 13, { align: "center" })

      // Photo circle background
      doc.setFillColor(240, 240, 240)
      doc.circle(16, 32, 10, "F")

      // Photo or initials
      if (student.photo) {
        try {
          const img = new Image()
          img.crossOrigin = "anonymous"
          img.src = student.photo
          await new Promise((resolve) => {
            img.onload = resolve
            img.onerror = resolve
            setTimeout(resolve, 3000)
          })
          const canvas = document.createElement("canvas")
          canvas.width = 100
          canvas.height = 100
          const ctx = canvas.getContext("2d")
          if (ctx) {
            ctx.beginPath()
            ctx.arc(50, 50, 50, 0, Math.PI * 2)
            ctx.clip()
            ctx.drawImage(img, 0, 0, 100, 100)
          }
          const imgData = canvas.toDataURL("image/jpeg")
          doc.addImage(imgData, "JPEG", 6, 22, 20, 20)
        } catch {}
      } else {
        doc.setFillColor(37, 99, 235)
        doc.circle(16, 32, 10, "F")
        doc.setTextColor(255, 255, 255)
        doc.setFontSize(10)
        doc.setFont("helvetica", "bold")
        doc.text(
          `${student.firstName[0]}${student.lastName[0]}`,
          16, 35, { align: "center" }
        )
      }

      // Student info
      doc.setTextColor(31, 41, 55)
      doc.setFontSize(9)
      doc.setFont("helvetica", "bold")
      doc.text(`${student.firstName} ${student.lastName}`, 30, 24)

      doc.setFontSize(6.5)
      doc.setFont("helvetica", "normal")
      doc.setTextColor(100, 100, 100)
      doc.text("Student ID", 30, 30)
      doc.setTextColor(31, 41, 55)
      doc.setFont("helvetica", "bold")
      doc.setFontSize(7)
      doc.text(student.studentId, 30, 35)

      doc.setFontSize(6.5)
      doc.setFont("helvetica", "normal")
      doc.setTextColor(100, 100, 100)
      doc.text("Class", 30, 41)
      doc.setTextColor(31, 41, 55)
      doc.setFont("helvetica", "bold")
      doc.setFontSize(7)
      doc.text(student.class?.name || "N/A", 30, 46)

      // Footer
      doc.setFillColor(243, 244, 246)
      doc.rect(0, 49, 85.6, 5, "F")
      doc.setTextColor(150, 150, 150)
      doc.setFontSize(4.5)
      doc.setFont("helvetica", "normal")
      doc.text("Generated by JETS School Management System", 42.8, 52.5, { align: "center" })

      doc.save(`${student.firstName}_${student.lastName}_ID_Card.pdf`)
    } catch (err) {
      console.error(err)
      alert("Failed to generate ID card")
    } finally {
      setGeneratingID(false)
    }
  }

  if (loading) return (
    <div className="flex items-center justify-center py-24">
      <div className="text-gray-400">Loading...</div>
    </div>
  )

  if (!student) return (
    <div className="flex items-center justify-center py-24">
      <div className="text-gray-400">Student not found</div>
    </div>
  )

  return (
    <div className="p-4 md:p-8">

      {/* Back button */}
      <div className="mb-6">
        <Link href="/dashboard/students"
          className="text-sm text-gray-500 hover:text-blue-600 transition">
          ← Back to Students
        </Link>
      </div>

      {/* Student Header */}
      <div className="bg-white rounded-2xl shadow-sm p-6 mb-6">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            <div className="w-16 h-16 rounded-full overflow-hidden bg-blue-100 flex items-center justify-center text-2xl font-bold text-blue-600 flex-shrink-0">
              {student.photo ? (
                <img src={student.photo} alt={student.firstName} className="w-full h-full object-cover" />
              ) : (
                <span>{student.firstName[0]}{student.lastName[0]}</span>
              )}
            </div>
            <div>
              <h1 className="text-xl md:text-2xl font-bold text-gray-800">{student.firstName} {student.lastName}</h1>
              <p className="text-gray-400 text-sm">Student ID: {student.studentId}</p>
              <p className="text-gray-400 text-sm">Class: {student.class?.name || "No class assigned"}</p>
            </div>
          </div>
          <div className="flex flex-wrap gap-2">
            <button
              onClick={generateIDCard}
              disabled={generatingID}
              className="bg-green-500 text-white font-semibold px-4 py-2 rounded-full hover:bg-green-600 transition text-sm disabled:opacity-50">
              {generatingID ? "Generating..." : "🪪 Print ID Card"}
            </button>
            <Link href={`/dashboard/students/${id}/edit`}
              className="bg-blue-600 text-white font-semibold px-4 py-2 rounded-full hover:bg-blue-700 transition text-sm">
              ✏️ Edit
            </Link>
            <button
              onClick={handleDelete}
              disabled={deleting}
              className="bg-red-500 text-white font-semibold px-4 py-2 rounded-full hover:bg-red-600 transition text-sm disabled:opacity-50">
              {deleting ? "Deleting..." : "🗑️ Delete"}
            </button>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">

        {/* Grades */}
        <div className="bg-white rounded-2xl shadow-sm p-6">
          <h2 className="text-lg font-bold text-gray-800 mb-4">📊 Grades</h2>
          {grades.length === 0 ? (
            <p className="text-gray-400 text-sm text-center py-4">No grades recorded yet</p>
          ) : (
            <div className="flex flex-col gap-3">
              {grades.map((grade: any, i: number) => (
                <div key={i} className="flex items-center justify-between py-2 border-b border-gray-50">
                  <div>
                    <p className="font-medium text-gray-800 text-sm">{grade.subject}</p>
                    <p className="text-gray-400 text-xs">{grade.term}</p>
                  </div>
                  <span className={`text-sm font-bold px-3 py-1 rounded-full
                    ${grade.score >= 70 ? "bg-green-50 text-green-600" :
                      grade.score >= 50 ? "bg-yellow-50 text-yellow-600" :
                      "bg-red-50 text-red-600"}`}>
                    {grade.score}%
                  </span>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Attendance */}
        <div className="bg-white rounded-2xl shadow-sm p-6">
          <h2 className="text-lg font-bold text-gray-800 mb-4">📅 Attendance</h2>
          {attendance.length === 0 ? (
            <p className="text-gray-400 text-sm text-center py-4">No attendance recorded yet</p>
          ) : (
            <div className="flex flex-col gap-3">
              {attendance.slice(0, 10).map((record: any, i: number) => (
                <div key={i} className="flex items-center justify-between py-2 border-b border-gray-50">
                  <p className="text-gray-600 text-sm">{new Date(record.date).toLocaleDateString()}</p>
                  <span className={`text-sm font-bold px-3 py-1 rounded-full capitalize
                    ${record.status === "present" ? "bg-green-50 text-green-600" :
                      record.status === "late" ? "bg-yellow-50 text-yellow-600" :
                      "bg-red-50 text-red-600"}`}>
                    {record.status}
                  </span>
                </div>
              ))}
            </div>
          )}
        </div>

      </div>
    </div>
  )
}
